name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  IMAGE_NAME: ps220812/Docker_Test

jobs:
  image-build:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker-compose build --no-cache --force-rm

  test-image:

      needs: image-build
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Test the Docker image
        run: docker-compose up -d

  push-to-registry:

      needs: test-image
      name: Push Docker image to Docker hub

      runs-on: ubuntu-latest

      steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Docker build
        uses: docker/setup-buildx-action@v2

      - name: login to Docker hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}"
          push: true
          repository: docker_test
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
